org.example.App#main([Ljava/lang/String;)V=1
org.example.model.PlusTwo#increment()I=7
org.example.model.PlusOne#increment()I=5
org.example.model.PlusTwo#<init>()V=6
org.example.model.PlusOne#<init>()V=4
org.example.App#<init>()V=0
org.example.model.GetOne#getValue()I=3
org.example.model.GetOne#<init>()V=2
